### ISSUE TITLE
The indexer does not use the IndexNameMapper

### ISSUE THREAD

**Issue by Nek-** [jolicode/elastically#168]
Because the IndexNameMapper does not use the indexNameMapper, the prefix is never added to the index name. However, the IndexBuilder is using it and works with the prefix! It's highly disturbing.

https://github.com/jolicode/elastically/blob/96a52d1e99b848e97f3eb613dfa3cce0e892d64e/src/Indexer.php#L45

**Comment by BorbagUskada** [comment]
What is your goto ? Using the indexNameMapper everywhere ?

Along with the issue reported by @Nek- , one consequence is that I see no way as for now to retrieve dynamically `Index` instance solely from a class.

The IndexNameMapper contains several methods to return a _prefixed_ index name based on a class, but no way to retrieve non-prefixed index name. And since the `getIndex(string $name)` method of `Client` automatically prefix the given name, there's no way but to get double-prefixed index name, which means the `getIndex` has to be called with a non-dynamic non-prefixed index name (not crystal clear but I guess you get it).

I could take a look at it but I'd like to know the exact scope of it, since this seems to be a BC break.

**Comment by damienalexandre** [comment]
You are supposed to call Client->getIndex() to get a Index.

https://github.com/jolicode/elastically/blob/2a97fc8ee18eb5abb5b7b52e7d398fa96d1018e5/src/Client.php#L57

That means you should now the that Class FOO belong to index "yop".

If your application does not have this information, you could expose the config elsewhere:

https://github.com/jolicode/elastically/blob/2a97fc8ee18eb5abb5b7b52e7d398fa96d1018e5/tests/Symfony/config.yaml#L45-L46

Or maybe we should add a helper in the Client, like "getIndexFromObject"? Would that help?

**Comment by damienalexandre** [comment]
> one consequence is that I see no way as for now to retrieve dynamically Index instance solely from a class, but maybe I am missing something.

When using prefix, it make things harder, you are right.

You have multiple things:

- the real index name, like **dev_indexName_20241113"
- the alias name, like "dev_indexName"
- the pure index name, like "indexName"

You have methods in IndexNameMapper to help you with that:

```php
<?php

namespace App\Controller;

use JoliCode\Elastically\Client;
use JoliCode\Elastically\IndexBuilder;
use JoliCode\Elastically\IndexNameMapper;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(IndexBuilder $builder, IndexNameMapper $indexNameMapper, Client $client): JsonResponse
    {
        $index = $builder->createIndex('myfoobarindex');

        dump($index->getName());
        dump($indexNameMapper->getPureIndexName($index->getName()));
        dump($indexNameMapper->getIndexNameFromClass('App\Dto\Foobar'));
        dump($indexNameMapper->getPureIndexName(
            $indexNameMapper->getIndexNameFromClass('App\Dto\Foobar')
        ));
    }
}
```

![image](https://github.com/user-attachments/assets/fd7a5082-b297-4ba3-bbdf-9ce7f1600e4f)

I'm closing this issue as I don't see what can be fixed, but feel free to re-open if you have more informations to share!

Thanks
