### ISSUE TITLE
Alias is only on the last created index

### ISSUE THREAD

**Issue by AdrienBr** [jolicode/elastically#52]
Hi,
I'm new here so I'm not sure it is a real problem, but there's something I do not understand : 

When I create multiple indices "foobar_{date}" with the alias "foobar", only the last index is aliased. The former indices are not aliased anymore.

I work on V1.0.2 and ES 7.10.0

I hope someone can clarify this to me, thank you !

**Comment by ternel** [comment]
:wave: 

This is normal. Elastically creates a new index everytime you call `IndexBuilder->createIndex` and change the alias to te latest index with the method `markAsLive`. 
If you want to remove old indices because you don't need them anymore, there's a method `purgeOldIndices` in the [IndexBuilder.php](https://github.com/jolicode/elastically/blob/223752b125f17e7ccb8563adc0657c1eccfa3a94/src/IndexBuilder.php#L99).
Call it, and old indices will be removed.
See the doc here: https://github.com/jolicode/elastically/blob/223752b125f17e7ccb8563adc0657c1eccfa3a94/README.md#demo

**Comment by damienalexandre** [comment]
Actually the alias is only moved to the new index only if you call `$indexBuilder->markAsLive($index, 'beers');`.

But anyway, this is the intended behavior. You only want ONE index to be "live" at a time because this is where your searches are done. 

Does that answer your question?
May I recommend reeding https://jolicode.com/blog/introducing-elastically-our-elastica-ally too? 

Cheers

**Comment by AdrienBr** [comment]
Thank you for your quick replies !

Yes you answered my question, I read the entire documentation more carefully and the method I was looking for is `migrate`

As far as I understand, when I need to update my index while keeping the old data available, I need to call `migrate`, `markAsLive` and `purgeOldIndices`

Thank you 
Cheers

**Comment by damienalexandre** [comment]
Yes absolutely :+1: Thanks!
